### ISSUE TITLE
Kretanje tenka

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-065-simple-tank-battle#2]
Pravac ispaljivanja metaka i pravac kretanja kod tenkova su odvojeni.

Zadaci:
- razdvojite usmerenje osnove tenka i kupole
- upravljanje kupolom neka ostane preko miša
- tenk neka se okreće tasterima 'a' za levo i 'd' za desno

**Comment by SonanMilosevic1994** [comment]
Sva tri zadatka su ispravljena. Ispaljivanje metaka nisam uspeo bolje da implementiram.
